Release 3.9.0
git-svn-id: http://svn.fedorahosted.org/svn/logrotate/tags/r3-9-0@485 ec1272ba-9ed1-42ef-8245-99669996828e

diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -539,7 +539,7 @@ cleanup 17
 # ------------------------------- Test 17 ------------------------------------
 preptest test.log 17 1 0
 # log with 1 byte should not be rotated
-$RLR test-config.17 2>error.log
+$RLR test-config.17 -l logrotate.log 2>error.log
 
 grep "unexpected } (missing previous '{')" error.log >/dev/null
 if [ $? != 0 ]; then
@@ -548,6 +548,14 @@ if [ $? != 0 ]; then
 fi
 
 rm error.log
+
+grep "reading config file test-config.17" logrotate.log >/dev/null
+if [ $? != 0 ]; then
+	echo "There is no log output in logrotate.log"
+	exit 3
+fi
+
+rm -f logrotate.log
 
 checkoutput <<EOF
 test.log 0 zero
@@ -809,24 +817,28 @@ $RLR test-config.32 --force
 getfacl test.log|grep "user:nobody:rwx" >/dev/null
 if [ $? != 0 ]; then
 	echo "test.log must have user:nobody:rwx ACL"
+	getfacl test.log
 	exit 3
 fi
 
 getfacl test.log|grep "group::---" >/dev/null
 if [ $? != 0 ]; then
 	echo "test.log must have group::--- ACL"
+	getfacl test.log
 	exit 3
 fi
 
 getfacl test.log.1|grep "user:nobody:rwx" >/dev/null
 if [ $? != 0 ]; then
 	echo "test.log.1 must have user:nobody:rwx ACL"
+	getfacl test.log.1
 	exit 3
 fi
 
 getfacl test.log.1|grep "group::---" >/dev/null
 if [ $? != 0 ]; then
 	echo "test.log.1 must have group::--- ACL"
+	getfacl test.log.1
 	exit 3
 fi
 
@@ -1124,7 +1136,7 @@ cleanup 45
 
 # ------------------------------- Test 45 ------------------------------------
 # Test that prerotate and postrotate scripts are not called when sharedscripts
-# is defined and one rotation fails. File test.log should still be rotated.
+# is defined and one rotation fails
 preptest test.log 45 1
 
 touch scriptout
@@ -1139,8 +1151,7 @@ fi
 rm -f error.log
 
 checkoutput <<EOF
-test.log 0
-test.log.1 0 zero
+test.log 0 zero
 scriptout 0 
 EOF
 
@@ -1494,21 +1505,24 @@ rm -f test.log.2
 cleanup 60
 
 # ------------------------------- Test 60 ------------------------------------
-# Rotation should continue even when first log is removed during rotation
-preptest test.log 60 1
-echo test2 > test2.log
+# Test we log debug output using -l option when passed.
+preptest test.log 61 1 0
 
-$RLR test-config.60 2>error.log
+$RLR test-config.61 --force -l ./logrotate.log
 
-grep "error opening" error.log >/dev/null
+DATESTRING=$(/bin/date +%Y-%m-%d-%H)
+
+grep "reading config file test-config.61" logrotate.log >/dev/null
 if [ $? != 0 ]; then
-	echo "No error printed, but there should be one."
+	echo "There is no log output in logrotate.log"
 	exit 3
 fi
 
+rm -f logrotate.log
+
 checkoutput <<EOF
-test2.log 0
-test2.log.1 0 test2
+test.log 0
+test.log.$DATESTRING 0 zero
 EOF
 
 cleanup 61
@@ -1523,6 +1537,77 @@ DATESTRING=$(/bin/date +%Y-%m-%d-%H)
 checkoutput <<EOF
 test.log 0
 test.log.$DATESTRING 0 zero
+EOF
+
+# ------------------------------- Test 62 ------------------------------------
+# Rotate sparse file
+preptest test.log 24 1 0
+
+echo -n zero > test.log
+truncate -s 10M test.log
+echo x >> test.log
+
+cp test.log test.example
+
+SIZE_SPARSE_OLD=$(du test.log|awk '{print $1}')
+SIZE_OLD=$(du --apparent-size test.log|awk '{print $1}')
+$RLR test-config.24 --force
+SIZE_NEW=$(du --apparent-size test.log.1|awk '{print $1}')
+SIZE_SPARSE_NEW=$(du test.log.1|awk '{print $1}')
+
+if [ $SIZE_OLD != $SIZE_NEW ]; then
+	echo "Bad apparent size of sparse logs"
+	echo "test.log: $SIZE_OLD"
+	echo "test.log.1: $SIZE_NEW"
+	exit 3
+fi
+
+if [ $SIZE_SPARSE_OLD -gt 100 ] || [ $SIZE_SPARSE_NEW -gt 100 ]; then
+	echo "Bad size of sparse logs"
+	echo "test.log: $SIZE_SPARSE_OLD"
+	echo "test.log.1: $SIZE_SPARSE_NEW"
+	exit 3
+fi
+
+checkoutput <<EOF
+test.log 0
+test.log.1 0 zerox
+EOF
+
+cleanup 63
+
+# ------------------------------- Test 63 ------------------------------------
+# Rotate sparse file, no data should be lost when hole is in the end of file
+preptest test.log 24 1 0
+
+echo -n zero > test.log
+truncate -s 10M test.log
+
+cp test.log test.example
+
+SIZE_SPARSE_OLD=$(du test.log|awk '{print $1}')
+SIZE_OLD=$(du --apparent-size test.log|awk '{print $1}')
+$RLR test-config.24 --force
+SIZE_NEW=$(du --apparent-size test.log.1|awk '{print $1}')
+SIZE_SPARSE_NEW=$(du test.log.1|awk '{print $1}')
+
+if [ $SIZE_OLD != $SIZE_NEW ]; then
+    echo "Bad apparent size of sparse logs"
+    echo "test.log: $SIZE_OLD"
+    echo "test.log.1: $SIZE_NEW"
+    exit 3
+fi
+
+if [ $SIZE_SPARSE_OLD -gt 100 ] || [ $SIZE_SPARSE_NEW -gt 100 ]; then
+    echo "Bad size of sparse logs"
+    echo "test.log: $SIZE_SPARSE_OLD"
+    echo "test.log.1: $SIZE_SPARSE_NEW"
+    exit 3
+fi
+
+checkoutput <<EOF
+test.log 0
+test.log.1 0 zero
 EOF
 
 cleanup
